version: '3.4'

x-logging:
  &default-logging
  options:
    max-size: '10m'
    max-file: '5'
  driver: json-file

services:
  db:
    image: mariadb:10.3
    command: --transaction-isolation=READ-COMMITTED --log-bin=/var/log/mysql/mariadb-bin --binlog-format=ROW
    restart: unless-stopped
    logging: *default-logging
    volumes:
      - ${PATH_DATABASE:-/data/database}:/var/lib/mysql
    env_file:
      - .env

  redis:
    image: redis:5.0.5-alpine
    restart: unless-stopped
    logging: *default-logging

  nextcloud:
    image: nextcloud:16-apache
    restart: unless-stopped
    logging: *default-logging
    labels:
      - "traefik.backend=naturalis-nextcloud"
      - "traefik.enable=true"
      - "traefik.port=80"
      - "${SITE_URL:-traefik.frontend.rule=Host:content.museum.naturalis.nl}"
    volumes:
      - ${PATH_NEXTCLOUD:-/data/nextcloud}:/var/www/html
      - ${PATH_FILES:-/data/nextcloud}:/var/www/data
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - .env
    depends_on:
      - db
      - redis

  traefik:
    image: traefik:1.7.11
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 8081:8080
    networks:
      - default
      - web
    logging: *default-logging
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${TRAEFIK_TOML_FILE:-./traefik.dev.toml}:/traefik.toml
      - ${CERTDIR:-/etc/letsencrypt}:/etc/letsencrypt

networks:
    default:
    web:
        external: true
